---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Service:
    Description: Name of the service, propagated all over the place. Choose wisely.
    Type: String
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: must contain only lowercase letters and hyphens

  Stage:
    Description: Environment stage (deployment phase)
    Type: String
    AllowedValues:
      - beta
      - prod

Conditions:
  IsBeta: !Equals [!Ref Stage, beta]

Globals:
  Function:
    Environment:
      Variables:
        SERVICE: !Ref Service
        STACK: !Ref AWS::StackName
        STAGE: !Ref Stage
    Handler: main.handler
    MemorySize: 128
    Runtime: python3.7
    Timeout: 30

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: '../src/hello_world'
      # cfn-lint fails here, see
      # https://github.com/aws-cloudformation/cfn-python-lint/issues/582
      AutoPublishAlias: !Ref Stage
      DeploymentPreference:
        Type: !If [IsBeta, AllAtOnce, Canary10Percent5Minutes]
        Alarms:
          - !Ref HelloWorldErrorsAlarm

  HelloWorldErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub '${HelloWorld}:${Stage}'
        - Name: FunctionName
          Value: !Ref HelloWorld
        - Name: ExecutedVersion
          Value: !GetAtt HelloWorld.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
